// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationsApi.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotificationsApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251025055307_intialcreate")]
    partial class intialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotificationsApi.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("NotificationsApi.Models.NotificationMessage", b =>
                {
                    b.Property<int>("NotificationMessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("notificationmessageid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationMessageID"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createddate");

                    b.Property<int?>("DocumentTemplateID")
                        .HasColumnType("integer")
                        .HasColumnName("documenttemplateid");

                    b.Property<int?>("NoOfTimesToRepeat")
                        .HasColumnType("integer")
                        .HasColumnName("nooftimestorepeat");

                    b.Property<string>("NotificationBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notificationbody");

                    b.Property<string>("NotificationChannel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notificationchannel");

                    b.Property<string>("NotificationFooter")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notificationfooter");

                    b.Property<string>("NotificationHeading")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notificationheading");

                    b.Property<string>("NotificationSubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notificationsubject");

                    b.Property<int?>("RepeatEvery")
                        .HasColumnType("integer")
                        .HasColumnName("repeatevery");

                    b.Property<string>("RepeatNotification")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("repeatnotification");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updatedby");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updateddate");

                    b.Property<string>("UseDocumentTemplate")
                        .HasColumnType("text")
                        .HasColumnName("usedocumenttemplate");

                    b.HasKey("NotificationMessageID");

                    b.ToTable("notificationmessage", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
